### ISSUE TITLE
add ovirt node as host InstallFailed: If output plugin is elasticsearch, validate host address is set failed to execute

### ISSUE THREAD

**Issue by meilihao** [oVirt/ovirt-engine#895] opened 2023-11-28 08:36 UTC
**Affected version**

* oVirt Engine: ovirt-engine-4.5.4-1.el8.noarch
* Host OS Variant: ovirt-node-ng-installer-4.5.4-2022120615.el8.iso
* VDSM version: vdsm-4.50.3.4-1.el8.x86_64
* elasticsearch: no elasticsearch

**Describe the bug**

add ovirt node as host InstallFailed, got  "Task If output plugin is elasticsearch, validate host address is set failed to execute"

engine-setup conf:
```log
--== CONFIGURATION PREVIEW ==--
         
          Application mode                        : both
          Default SAN wipe after delete           : False
          Host FQDN                               : egnine.myovirt.com
          Firewall manager                        : firewalld
          Update Firewall                         : True
          Set up Cinderlib integration            : False
          Configure local Engine database         : True
          Set application as default page         : True
          Configure Apache SSL                    : True
          Keycloak installation                   : True
          Engine database host                    : localhost
          Engine database port                    : 5432
          Engine database secured connection      : False
          Engine database host name validation    : False
          Engine database name                    : engine
          Engine database user name               : engine
          Engine installation                     : True
          PKI organization                        : myovirt.com
          Set up ovirt-provider-ovn               : True
          DWH installation                        : True
          DWH database host                       : localhost
          DWH database port                       : 5432
          DWH database secured connection         : False
          DWH database host name validation       : False
          DWH database name                       : ovirt_engine_history
          Configure local DWH database            : True
          Grafana integration                     : True
          Grafana database user name              : ovirt_engine_history_grafana
          Keycloak database host                  : localhost
          Keycloak database port                  : 5432
          Keycloak database secured connection    : False
          Keycloak database host name validation  : False
          Keycloak database name                  : ovirt_engine_keycloak
          Keycloak database user name             : ovirt_engine_keycloak
          Configure local Keycloak database       : True
          Configure VMConsole Proxy               : True
          Configure WebSocket Proxy               : True
```

/var/log/ovirt-engine/host-deploy log:
```log
2023-11-28 12:12:56 CST - {
  "uuid" : "1b798377-1bd4-4276-b1bf-c428f3b0d858",
  "counter" : 693,
  "stdout" : "fatal: [192.168.88.151]: FAILED! => {\"msg\": \"The conditional check 'elasticsearch_host == None or elasticsearch_host is undefined' failed. The error was: error while evaluating conditional (elasticsearch_host == None or elasticsearch_host is undefined): 'elasticsearch_host' is undefined. 'elasticsearch_host' is undefined\\n\\nThe error appears to be in '/usr/share/ansible/roles/oVirt.metrics/roles/ovirt_initial_validations/tasks/check_logging_collectors.yml': line 4, column 3, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n\\n- name: If output plugin is elasticsearch, validate host address is set\\n  ^ here\\n\"}",
  "start_line" : 675,
  "end_line" : 676,
  "runner_ident" : "3be7ae0e-45a9-4d22-b404-1b2d4a8bef93",
  "event" : "runner_on_failed",
  "pid" : 26214,
  "created" : "2023-11-28T04:12:54.555605",
  "parent_uuid" : "000c295d-9782-b198-f972-00000000069d",
  "event_data" : {
    "playbook" : "ovirt-host-deploy.yml",
    "playbook_uuid" : "221c54c8-8f78-4e72-8ca4-8ae342f75f5b",
    "play" : "all",
    "play_uuid" : "000c295d-9782-b198-f972-000000000002",
    "play_pattern" : "all",
    "task" : "If output plugin is elasticsearch, validate host address is set",
    "task_uuid" : "000c295d-9782-b198-f972-00000000069d",
    "task_action" : "debug",
    "task_args" : "",
    "task_path" : "/usr/share/ansible/roles/oVirt.metrics/roles/ovirt_initial_validations/tasks/check_logging_collectors.yml:4",
    "role" : "oVirt.metrics/roles/ovirt_initial_validations",
    "host" : "192.168.88.151",
    "remote_addr" : "192.168.88.151",
    "res" : {
      "msg" : "The conditional check 'elasticsearch_host == None or elasticsearch_host is undefined' failed. The error was: error while evaluating conditional (elasticsearch_host == None or elasticsearch_host is undefined): 'elasticsearch_host' is undefined. 'elasticsearch_host' is undefined\n\nThe error appears to be in '/usr/share/ansible/roles/oVirt.metrics/roles/ovirt_initial_validations/tasks/check_logging_collectors.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: If output plugin is elasticsearch, validate host address is set\n  ^ here\n",
      "_ansible_no_log" : false
    },
    "start" : "2023-11-28T04:12:54.509285",
    "end" : "2023-11-28T04:12:54.555134",
    "duration" : 0.045849,
    "ignore_errors" : null,
    "event_loop" : null,
    "uuid" : "1b798377-1bd4-4276-b1bf-c428f3b0d858"
  }
}

**To reproduce**

1. add dc
2. add cluster
3. add host

**Expected behavior**
add host ok

**Comment by michalskrivanek** [comment] 2023-11-28 08:53
duplicate of https://github.com/oVirt/ovirt-ansible-collection/issues/708

**Comment by michalskrivanek** [comment] 2023-11-28 08:53
(and fixed by https://github.com/oVirt/ovirt-ansible-collection/issues/708#issuecomment-1592460296 )

**Closed by michalskrivanek** 2023-11-28 08:53 UTC
Labels: bug
