### ISSUE TITLE
network out of sync on CentOS9

### ISSUE THREAD

**Issue by kandadeepak** [oVirt/ovirt-engine#944] opened 2024-05-14 20:48 UTC
Currently using the oVirt version 4.5.6 on redhat 8.9 operating system

oVirt Version:4.5.6-1.el8
OS Version : CentOS Stream release 9
ovsdb-server (Open vSwitch) 2.17.10
vdsm - vdsm-4.50.5.1-1.el9.x86_64

Issue

While adding the Centos Stream 9 based oVirt Node into manager network goes to out of sync where as customized(Prebuild oVirt node) works without any out of sync.

When adding the Centos 9 base node into oVirt manager the gateway/dns getting flushed and Network's Configuration differ from DC.

**To reproduce**

Deploy new centos 9 node and steps for package and then add the node to manager.

[root@node01 ~]# dnf -y install centos-release-ovirt45
[root@node01 ~]# dnf -y install qemu-kvm libvirt virt-install vdsm cockpit
[root@node01 ~]# systemctl enable --now libvirtd cockpit.socket

![image](https://github.com/oVirt/ovirt-engine/assets/5003527/047bf799-d8c5-4e5d-9ad6-2a3c40da4117)
**Expected behavior**

Not out of sync network error message should be populated.

**Comment by dupondje** [comment] 2024-05-15 09:41
Your screenshot is unreadable.
But most likely this is caused by newer libnl version.

Fixed in https://github.com/oVirt/vdsm/commit/49eaf70c5a14eb00e85eac5f91ac36f010a9a327

**Closed by dupondje** 2024-05-15 09:41 UTC
Labels: bug

**Comment by kandadeepak** [comment] 2024-05-15 12:40
When I tried with oVirt manager(Redhat 9) and oVirt node(CentOS 9) on the VDSM shows the following error and screenshot

2024-05-15 07:51:26,088-0400 ERROR (jsonrpc/6) [jsonrpc.JsonRpcServer] Internal server error (__init__:343)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/yajsonrpc/__init__.py", line 338, in _handle_request
    res = method(**params)
  File "/usr/lib/python3.9/site-packages/vdsm/rpc/Bridge.py", line 186, in _dynamicMethod
    result = fn(*methodArgs)
  File "<decorator-gen-508>", line 2, in setupNetworks
  File "/usr/lib/python3.9/site-packages/vdsm/common/api.py", line 33, in method
    ret = func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/vdsm/API.py", line 1576, in setupNetworks
    supervdsm.getProxy().setupNetworks(networks, bondings, options)
  File "/usr/lib/python3.9/site-packages/vdsm/common/supervdsm.py", line 38, in __call__
    return callMethod()
  File "/usr/lib/python3.9/site-packages/vdsm/common/supervdsm.py", line 35, in <lambda>
    getattr(self._supervdsmProxy._svdsm, self._funcName)(*args,
  File "<string>", line 2, in setupNetworks
  File "/usr/lib64/python3.9/multiprocessing/managers.py", line 825, in _callmethod
    raise convert_to_error(kind, result)
libnmstate.error.NmstateValueError: Failed to find suitable interface for saving DNS name servers: 10.209.66.100, nmstate only support saving DNS to interface with static gateway or auto interface with auto-dns:false

Error while save the config
![image](https://github.com/oVirt/ovirt-engine/assets/5003527/27b16d41-67f0-4359-b976-91f1b42f8bf8)

Do you have any workaround or fix in near future?
