### ISSUE TITLE
Users Allocation to PoolVM remains even after VM detachment/deletion

### ISSUE THREAD

**Issue by Arrakaij** [oVirt/ovirt-engine#179] opened 2022-03-22 17:10 UTC
Good Evening

When a user logs in to VM-Portal and requests a VM from a Pool, this assignment remains even after the according VM gets shutdown, detached or deleted, resulting in unexpected (from a user point of view 'weird') behaviour. In case of deletion of the attached VM, oVirt tries to start the non-existing VM. After some time the attachment to a specific VM gets lost and everything works again as normal; However, even in a normal production enviroment this may result in some unwanted behaviour.

See additional info for other problems and my thoughts on solutions

Engine Version:  Version 4.4.10.7-1.el8 
Cluster Comb. Level: 4.6

Steps to Reproduce:
1. Setup a Pool of VM (for us Windows using sysprep)
2. Login as a user, request a VM from that pool, login to the VM
3. Shutdown the VM as User (from inside or WebUI)
4. Logout as a User
5. Login as Admin, detach and delete the VM the user is bound to
6. Login as User and request a VM from the pool

Actual results:
The System requests the non-existing VM from the Pool, resulting in an error

Expected results:
The System requests any functioning VM.

Additional info:

Another - for us - unwanted scenario: The User wants to get a fresh VM.
He shuts down his VM; After that the user can request a new VM from the Pool. But instead of oVirt giving any already prepared VMs, the user gets the same VM he had before - and now he has to sit through all the sysprep work that is done when a VM from the pool is setup. This maybe wanted, but it can be painful.

Feature enhancement request:

Solutions i thought about. They are not mutually exclusive, all of them would be nice.
1)
Let the API have a function "deallocateVm" similar to "allocateVm" ( http://ovirt.github.io/ovirt-engine-api-model/4.5/#services/vm_pool ) It removes the allocation between user and vm and guarantees a fresh start. The function may have a parameter on what to do with the VM is attached to (shutdown, restart, ...)
This way any software can force a deallocation (And the WebUI should have that option then)
2) I know the behavior can be wanted, so add an Parameter to a Pool, an "User Allocation Policy", which could be:
- Same User (try to allocate the same VM to the same user as long as possible; if all vms already have an allocation, allocate the vm that belongs to the user that was not seen the longest time; This is kind of the situation we have now)
- Bind to User (Same as "Same", but if all VMs are bound, throw an error)
- Bind to User and Extend (Same as Bind to User, but extend the pool by 1 machine every time a new user requests a vm)
[The Bind to User settings may have a timeout that deletes the binding when the user was absent for a certain period of time)
- Any (Ignore bindings, just hand out any VM that is ready, except the user is logged in into a VM)

**Comment by sandrobonazzola** [comment] 2022-03-23 10:22
@ahadas can you please triage?

**Comment by sgratch** [comment] 2022-03-23 12:49
@sandrobonazzola @ahadas @Arrakaij 
This seems like a web-ui issue and as a follow up issue to this https://github.com/oVirt/ovirt-web-ui/issues/719.
The specific scenario described above (an error after de-touching a vm from the pool) is not reproduced to me but anyway it seems a problem due to wrong permission assignment. Please check https://github.com/oVirt/ovirt-web-ui/issues/719#issuecomment-741924942. 
We added that permissions requirement to our documentation as well. 

let's re-open this issue under [web-ui project](https://github.com/oVirt/ovirt-web-ui/issues) and continue the discussion there.

**Comment by ahadas** [comment] 2022-03-23 14:23
Great, thanks Sharon - I suspected this is a web-ui issue but didn't want to move before giving it some more thought
If you can also check gchat - there's another thing that waits for your feedback :)

**Comment by sandrobonazzola** [comment] 2022-03-24 06:45
closing this issue as duplicate of https://github.com/oVirt/ovirt-web-ui/issues/1574 then, thanks.

**Closed by sandrobonazzola** 2022-03-24 06:45 UTC
Labels: virt
